/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/YogaPercentageSpec.html


using facebook.yoga.Enums;

import facebook.Yoga;

import facebook.yoga.*;

import utest.Assert;

class YogaPercentageSpec {

  public function new(){}
  public function test_percentage_width_height() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidthPercent(root_child0, 30);
    Yoga.nodeStyleSetHeightPercent(root_child0, 30);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(140, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_percentage_position_left_top() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 400);
    Yoga.nodeStyleSetHeight(root, 400);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetPositionPercent(root_child0, Edge.Left, 10);
    Yoga.nodeStyleSetPositionPercent(root_child0, Edge.Top, 20);
    Yoga.nodeStyleSetWidthPercent(root_child0, 45);
    Yoga.nodeStyleSetHeightPercent(root_child0, 55);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(400, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(400, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(40, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(180, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(220, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(400, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(400, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(260, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(180, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(220, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_percentage_position_bottom_right() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 500);
    Yoga.nodeStyleSetHeight(root, 500);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetPositionPercent(root_child0, Edge.Right, 20);
    Yoga.nodeStyleSetPositionPercent(root_child0, Edge.Bottom, 10);
    Yoga.nodeStyleSetWidthPercent(root_child0, 55);
    Yoga.nodeStyleSetHeightPercent(root_child0, 15);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(500, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(500, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(-100, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(275, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(500, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(500, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(125, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(275, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_percentage_flex_basis() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 25);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(125, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(125, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(125, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_cross() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 25);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(125, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(125, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(125, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(125, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_cross_min_height() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMinHeightPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 2);
    Yoga.nodeStyleSetMinHeightPercent(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(140, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(140, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(140, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(140, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_main_max_height() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 10);
    Yoga.nodeStyleSetMaxHeightPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 4);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 10);
    Yoga.nodeStyleSetMaxHeightPercent(root_child1, 20);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(52, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(148, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(148, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(148, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_cross_max_height() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 10);
    Yoga.nodeStyleSetMaxHeightPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 4);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 10);
    Yoga.nodeStyleSetMaxHeightPercent(root_child1, 20);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(120, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(120, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_main_max_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 15);
    Yoga.nodeStyleSetMaxWidthPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 4);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 10);
    Yoga.nodeStyleSetMaxWidthPercent(root_child1, 20);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(120, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(80, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(40, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_cross_max_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 10);
    Yoga.nodeStyleSetMaxWidthPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 4);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 15);
    Yoga.nodeStyleSetMaxWidthPercent(root_child1, 20);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(80, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(160, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(40, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_main_min_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 15);
    Yoga.nodeStyleSetMinWidthPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 4);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 10);
    Yoga.nodeStyleSetMinWidthPercent(root_child1, 20);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(120, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(80, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(120, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_flex_basis_cross_min_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 10);
    Yoga.nodeStyleSetMinWidthPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 4);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 15);
    Yoga.nodeStyleSetMinWidthPercent(root_child1, 20);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_multiple_nested_with_padding_margin_and_percentage_values() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Left, 5);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Top, 5);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Right, 5);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Bottom, 5);
    Yoga.nodeStyleSetPadding(root_child0, Edge.Left, 3);
    Yoga.nodeStyleSetPadding(root_child0, Edge.Top, 3);
    Yoga.nodeStyleSetPadding(root_child0, Edge.Right, 3);
    Yoga.nodeStyleSetPadding(root_child0, Edge.Bottom, 3);
    Yoga.nodeStyleSetMinWidthPercent(root_child0, 60);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0_child0, Edge.Left, 5);
    Yoga.nodeStyleSetMargin(root_child0_child0, Edge.Top, 5);
    Yoga.nodeStyleSetMargin(root_child0_child0, Edge.Right, 5);
    Yoga.nodeStyleSetMargin(root_child0_child0, Edge.Bottom, 5);
    Yoga.nodeStyleSetPaddingPercent(root_child0_child0, Edge.Left, 3);
    Yoga.nodeStyleSetPaddingPercent(root_child0_child0, Edge.Top, 3);
    Yoga.nodeStyleSetPaddingPercent(root_child0_child0, Edge.Right, 3);
    Yoga.nodeStyleSetPaddingPercent(root_child0_child0, Edge.Bottom, 3);
    Yoga.nodeStyleSetWidthPercent(root_child0_child0, 50);
    Yoga.nodeInsertChild(root_child0, root_child0_child0, 0);

    var root_child0_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginPercent(root_child0_child0_child0, Edge.Left, 5);
    Yoga.nodeStyleSetMarginPercent(root_child0_child0_child0, Edge.Top, 5);
    Yoga.nodeStyleSetMarginPercent(root_child0_child0_child0, Edge.Right, 5);
    Yoga.nodeStyleSetMarginPercent(root_child0_child0_child0, Edge.Bottom, 5);
    Yoga.nodeStyleSetPadding(root_child0_child0_child0, Edge.Left, 3);
    Yoga.nodeStyleSetPadding(root_child0_child0_child0, Edge.Top, 3);
    Yoga.nodeStyleSetPadding(root_child0_child0_child0, Edge.Right, 3);
    Yoga.nodeStyleSetPadding(root_child0_child0_child0, Edge.Bottom, 3);
    Yoga.nodeStyleSetWidthPercent(root_child0_child0_child0, 45);
    Yoga.nodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 4);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 15);
    Yoga.nodeStyleSetMinWidthPercent(root_child1, 20);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(5, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(5, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(190, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(48, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(8, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(8, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(92, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0_child0_child0));
    Assert.floatEquals(36, Yoga.nodeLayoutGetWidth(root_child0_child0_child0));
    Assert.floatEquals(6, Yoga.nodeLayoutGetHeight(root_child0_child0_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(58, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(142, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(5, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(5, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(190, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(48, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(90, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(8, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(92, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(46, Yoga.nodeLayoutGetLeft(root_child0_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0_child0_child0));
    Assert.floatEquals(36, Yoga.nodeLayoutGetWidth(root_child0_child0_child0));
    Assert.floatEquals(6, Yoga.nodeLayoutGetHeight(root_child0_child0_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(58, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(142, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_percentage_margin_should_calculate_based_only_on_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMarginPercent(root_child0, Edge.Left, 10);
    Yoga.nodeStyleSetMarginPercent(root_child0, Edge.Top, 10);
    Yoga.nodeStyleSetMarginPercent(root_child0, Edge.Right, 10);
    Yoga.nodeStyleSetMarginPercent(root_child0, Edge.Bottom, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0_child0, 10);
    Yoga.nodeStyleSetHeight(root_child0_child0, 10);
    Yoga.nodeInsertChild(root_child0, root_child0_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(20, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(160, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(20, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(160, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0_child0));
  }

  public function test_percentage_padding_should_calculate_based_only_on_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetPaddingPercent(root_child0, Edge.Left, 10);
    Yoga.nodeStyleSetPaddingPercent(root_child0, Edge.Top, 10);
    Yoga.nodeStyleSetPaddingPercent(root_child0, Edge.Right, 10);
    Yoga.nodeStyleSetPaddingPercent(root_child0, Edge.Bottom, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0_child0, 10);
    Yoga.nodeStyleSetHeight(root_child0_child0, 10);
    Yoga.nodeInsertChild(root_child0, root_child0_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(20, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(170, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0_child0));
  }

  public function test_percentage_absolute_position() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetPositionType(root_child0, PositionType.Absolute);
    Yoga.nodeStyleSetPositionPercent(root_child0, Edge.Left, 30);
    Yoga.nodeStyleSetPositionPercent(root_child0, Edge.Top, 10);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(60, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(60, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_percentage_width_height_undefined_parent_size() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidthPercent(root_child0, 50);
    Yoga.nodeStyleSetHeightPercent(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_percent_within_flex_grow() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 350);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 100);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child1_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidthPercent(root_child1_child0, 100);
    Yoga.nodeInsertChild(root_child1, root_child1_child0, 0);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 100);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(350, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(150, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(250, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(350, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(250, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(150, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_percentage_container_in_wrapping_container() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root_child0_child0, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root_child0_child0, Justify.Center);
    Yoga.nodeStyleSetWidthPercent(root_child0_child0, 100);
    Yoga.nodeInsertChild(root_child0, root_child0_child0, 0);

    var root_child0_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0_child0_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0_child0_child0, 50);
    Yoga.nodeInsertChild(root_child0_child0, root_child0_child0_child0, 0);

    var root_child0_child0_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0_child0_child1, 50);
    Yoga.nodeStyleSetHeight(root_child0_child0_child1, 50);
    Yoga.nodeInsertChild(root_child0_child0, root_child0_child0_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0_child0));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0_child0_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0_child0_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0_child0_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0_child1));
  }

  public function test_percent_absolute_position() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 60);
    Yoga.nodeStyleSetHeight(root, 50);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root_child0, FlexDirection.Row);
    Yoga.nodeStyleSetPositionType(root_child0, PositionType.Absolute);
    Yoga.nodeStyleSetPositionPercent(root_child0, Edge.Left, 50);
    Yoga.nodeStyleSetWidthPercent(root_child0, 100);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidthPercent(root_child0_child0, 100);
    Yoga.nodeInsertChild(root_child0, root_child0_child0, 0);

    var root_child0_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidthPercent(root_child0_child1, 100);
    Yoga.nodeInsertChild(root_child0, root_child0_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(30, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(60, Yoga.nodeLayoutGetLeft(root_child0_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child1));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(30, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(-60, Yoga.nodeLayoutGetLeft(root_child0_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child1));
    Assert.floatEquals(60, Yoga.nodeLayoutGetWidth(root_child0_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0_child1));
  }

}
