/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/YogaJustifyContentSpec.html


using facebook.yoga.Enums;

import facebook.Yoga;

import facebook.yoga.*;

import utest.Assert;

class YogaJustifyContentSpec {

  public function new(){}
  public function test_justify_content_row_flex_start() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(20, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(92, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(82, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(72, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_row_flex_end() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.FlexEnd);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(72, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(82, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(92, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(20, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_row_center() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(36, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(46, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(56, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(56, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(46, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(36, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_row_space_between() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.SpaceBetween);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(46, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(92, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(92, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(46, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_row_space_around() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.SpaceAround);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(12, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(46, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(80, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(80, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(46, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(12, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_column_flex_start() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_column_flex_end() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.FlexEnd);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(82, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(92, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(82, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(92, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_column_center() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(36, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(56, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(36, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(56, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_column_space_between() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.SpaceBetween);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(92, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(92, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_column_space_around() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.SpaceAround);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(12, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(12, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_row_min_width_and_margin() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetMargin(root, Edge.Left, 100);
    Yoga.nodeStyleSetMinWidth(root, 50);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 20);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(15, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(15, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_justify_content_row_max_width_and_margin() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetMargin(root, Edge.Left, 100);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetMaxWidth(root, 80);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 20);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(30, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(30, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_justify_content_column_min_height_and_margin() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetMargin(root, Edge.Top, 100);
    Yoga.nodeStyleSetMinHeight(root, 50);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 20);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(15, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(15, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_justify_content_colunn_max_height_and_margin() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetMargin(root, Edge.Top, 100);
    Yoga.nodeStyleSetHeight(root, 100);
    Yoga.nodeStyleSetMaxHeight(root, 80);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 20);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(80, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(30, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(80, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(30, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_justify_content_column_space_evenly() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.SpaceEvenly);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(18, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(74, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(18, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(46, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(74, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_justify_content_row_space_evenly() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.SpaceEvenly);
    Yoga.nodeStyleSetWidth(root, 102);
    Yoga.nodeStyleSetHeight(root, 102);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(26, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(51, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(77, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(102, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(77, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(51, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(26, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));
  }

}
