/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/YogaMarginSpec.html


using facebook.yoga.Enums;

import facebook.Yoga;

import facebook.yoga.*;

import utest.Assert;

class YogaMarginSpec {

  public function new(){}
  public function test_margin_start() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Start, 10);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(80, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_top() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Top, 10);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_end() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetJustifyContent(root, Justify.FlexEnd);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.End, 10);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(80, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_bottom() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.FlexEnd);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Bottom, 10);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_and_flex_row() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Start, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.End, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_and_flex_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Top, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Bottom, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_and_stretch_row() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Top, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Bottom, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_and_stretch_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Start, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.End, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(80, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_with_sibling_row() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMargin(root_child0, Edge.End, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(45, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(55, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(45, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(55, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(45, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(45, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_with_sibling_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Bottom, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(45, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(55, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(45, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(45, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(55, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(45, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_bottom() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Bottom);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_top() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Top);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_bottom_and_top() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Top);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Bottom);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_bottom_and_top_justify_center() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Top);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Bottom);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_mutiple_children_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Top);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child1, Edge.Top);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 50);
    Yoga.nodeStyleSetHeight(root_child2, 50);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(25, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(25, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_margin_auto_mutiple_children_row() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child1, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 50);
    Yoga.nodeStyleSetHeight(root_child2, 50);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(125, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_margin_auto_left_and_right_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_left_and_right() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_start_and_end_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Start);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.End);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_start_and_end() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Start);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.End);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_left_and_right_column_and_center() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_left() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_right() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_left_and_right_strech() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_top_and_bottom_strech() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Top);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Bottom);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_should_not_be_part_of_max_height() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 250);
    Yoga.nodeStyleSetHeight(root, 250);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Top, 20);
    Yoga.nodeStyleSetWidth(root_child0, 100);
    Yoga.nodeStyleSetHeight(root_child0, 100);
    Yoga.nodeStyleSetMaxHeight(root_child0, 100);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(20, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_should_not_be_part_of_max_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 250);
    Yoga.nodeStyleSetHeight(root, 250);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Left, 20);
    Yoga.nodeStyleSetWidth(root_child0, 100);
    Yoga.nodeStyleSetMaxWidth(root_child0, 100);
    Yoga.nodeStyleSetHeight(root_child0, 100);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(20, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(250, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(150, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_auto_left_right_child_bigger_than_parent() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetWidth(root, 52);
    Yoga.nodeStyleSetHeight(root, 52);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 72);
    Yoga.nodeStyleSetHeight(root_child0, 72);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(-20, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_auto_left_child_bigger_than_parent() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetWidth(root, 52);
    Yoga.nodeStyleSetHeight(root, 52);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetWidth(root_child0, 72);
    Yoga.nodeStyleSetHeight(root_child0, 72);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(-20, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_fix_left_auto_right_child_bigger_than_parent() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetWidth(root, 52);
    Yoga.nodeStyleSetHeight(root, 52);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Left, 10);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Right);
    Yoga.nodeStyleSetWidth(root_child0, 72);
    Yoga.nodeStyleSetHeight(root_child0, 72);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(10, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(-20, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_auto_left_fix_right_child_bigger_than_parent() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetJustifyContent(root, Justify.Center);
    Yoga.nodeStyleSetWidth(root, 52);
    Yoga.nodeStyleSetHeight(root, 52);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Right, 10);
    Yoga.nodeStyleSetWidth(root_child0, 72);
    Yoga.nodeStyleSetHeight(root_child0, 72);
    Yoga.nodeInsertChild(root, root_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(52, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(-30, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(-10, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(72, Yoga.nodeLayoutGetHeight(root_child0));
  }

  public function test_margin_auto_top_stretching_child() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexShrink(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 0);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Top);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(100, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_margin_auto_left_stretching_child() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetAlignItems(root, Align.Center);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 200);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexShrink(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 0);
    Yoga.nodeStyleSetMarginAuto(root_child0, Edge.Left);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(200, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(200, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(150, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(150, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));
  }

}
