/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/YogaFlexSpec.html


using facebook.yoga.Enums;

import facebook.Yoga;

import facebook.yoga.*;

import utest.Assert;

class YogaFlexSpec {

  public function new(){}
  public function test_flex_basis_flex_grow_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(75, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_flex_basis_flex_grow_row() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(75, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(25, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(75, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_flex_basis_flex_shrink_column() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexShrink(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 100);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexBasis(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_flex_basis_flex_shrink_row() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexShrink(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 100);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexBasis(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_flex_shrink_to_zero() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root, 75);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 50);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexShrink(root_child1, 1);
    Yoga.nodeStyleSetWidth(root_child1, 50);
    Yoga.nodeStyleSetHeight(root_child1, 50);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child2, 50);
    Yoga.nodeStyleSetHeight(root_child2, 50);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(75, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_flex_basis_overrides_main_size() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(60, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(60, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(60, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(80, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(20, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_flex_grow_shrink_at_most() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0_child0, 1);
    Yoga.nodeStyleSetFlexShrink(root_child0_child0, 1);
    Yoga.nodeInsertChild(root_child0, root_child0_child0, 0);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_flex_grow_less_than_factor_one() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 200);
    Yoga.nodeStyleSetHeight(root, 500);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 0.2);
    Yoga.nodeStyleSetFlexBasis(root_child0, 40);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 0.2);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 0.4);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(500, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(132, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(132, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(92, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(224, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(184, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(500, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(132, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(132, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(92, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(224, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(200, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(184, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

}
