/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/YogaRoundingSpec.html


using facebook.yoga.Enums;

import facebook.Yoga;

import facebook.yoga.*;

import utest.Assert;

class YogaRoundingSpec {

  public function new(){}
  public function test_rounding_flex_basis_flex_grow_row_width_of_100() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(33, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(33, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(34, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(67, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(33, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(67, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(33, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(33, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(34, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(33, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_flex_basis_flex_grow_row_prime_number_width() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 113);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeInsertChild(root, root_child2, 2);

    var root_child3 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child3, 1);
    Yoga.nodeInsertChild(root, root_child3, 3);

    var root_child4 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child4, 1);
    Yoga.nodeInsertChild(root, root_child4, 4);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(23, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(23, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(22, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(45, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(23, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Assert.floatEquals(68, Yoga.nodeLayoutGetLeft(root_child3));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child3));
    Assert.floatEquals(22, Yoga.nodeLayoutGetWidth(root_child3));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child3));

    Assert.floatEquals(90, Yoga.nodeLayoutGetLeft(root_child4));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child4));
    Assert.floatEquals(23, Yoga.nodeLayoutGetWidth(root_child4));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child4));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(90, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(23, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(68, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(22, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(45, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(23, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Assert.floatEquals(23, Yoga.nodeLayoutGetLeft(root_child3));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child3));
    Assert.floatEquals(22, Yoga.nodeLayoutGetWidth(root_child3));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child3));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child4));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child4));
    Assert.floatEquals(23, Yoga.nodeLayoutGetWidth(root_child4));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child4));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_flex_basis_flex_shrink_row() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 101);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexShrink(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 100);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexBasis(root_child1, 25);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexBasis(root_child2, 25);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(101, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(51, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(51, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(76, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(25, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(101, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(51, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(25, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(25, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_flex_basis_overrides_main_size() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 113);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(64, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(64, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_total_fractial() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 87.4);
    Yoga.nodeStyleSetHeight(root, 113.4);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 0.7);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50.3);
    Yoga.nodeStyleSetHeight(root_child0, 20.3);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1.6);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1.1);
    Yoga.nodeStyleSetHeight(root_child2, 10.7);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(59, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(59, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(30, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(59, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(59, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(30, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_total_fractial_nested() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 87.4);
    Yoga.nodeStyleSetHeight(root, 113.4);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 0.7);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50.3);
    Yoga.nodeStyleSetHeight(root_child0, 20.3);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child0_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0_child0, 0.3);
    Yoga.nodeStyleSetPosition(root_child0_child0, Edge.Bottom, 13.3);
    Yoga.nodeStyleSetHeight(root_child0_child0, 9.9);
    Yoga.nodeInsertChild(root_child0, root_child0_child0, 0);

    var root_child0_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0_child1, 4);
    Yoga.nodeStyleSetFlexBasis(root_child0_child1, 0.3);
    Yoga.nodeStyleSetPosition(root_child0_child1, Edge.Top, 13.3);
    Yoga.nodeStyleSetHeight(root_child0_child1, 1.1);
    Yoga.nodeInsertChild(root_child0, root_child0_child1, 1);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1.6);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1.1);
    Yoga.nodeStyleSetHeight(root_child2, 10.7);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(59, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(-13, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(12, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetTop(root_child0_child1));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0_child1));
    Assert.floatEquals(47, Yoga.nodeLayoutGetHeight(root_child0_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(59, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(30, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(59, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child0));
    Assert.floatEquals(-13, Yoga.nodeLayoutGetTop(root_child0_child0));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0_child0));
    Assert.floatEquals(12, Yoga.nodeLayoutGetHeight(root_child0_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetTop(root_child0_child1));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child0_child1));
    Assert.floatEquals(47, Yoga.nodeLayoutGetHeight(root_child0_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(59, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(30, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(87, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_fractial_input_1() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 113.4);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(64, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(64, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_fractial_input_2() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 113.6);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(114, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(65, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(65, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(114, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(65, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(65, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_fractial_input_3() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetPosition(root, Edge.Top, 0.3);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 113.4);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(114, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(65, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(114, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(65, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_fractial_input_4() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetPosition(root, Edge.Top, 0.7);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 113.4);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexBasis(root_child0, 50);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(1, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(64, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(1, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(113, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(64, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(64, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(25, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(89, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(24, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_inner_node_controversy_horizontal() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 320);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetHeight(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeight(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child1_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1_child0, 1);
    Yoga.nodeStyleSetHeight(root_child1_child0, 10);
    Yoga.nodeInsertChild(root_child1, root_child1_child0, 0);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeight(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(320, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(107, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(107, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(106, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(106, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(213, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(107, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(320, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(213, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(107, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(107, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(106, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(106, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(107, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_inner_node_controversy_vertical() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetHeight(root, 320);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetWidth(root_child0, 10);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetWidth(root_child1, 10);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child1_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1_child0, 1);
    Yoga.nodeStyleSetWidth(root_child1_child0, 10);
    Yoga.nodeInsertChild(root_child1, root_child1_child0, 0);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetWidth(root_child2, 10);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(107, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(213, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(107, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(213, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(10, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

  public function test_rounding_inner_node_controversy_combined() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 640);
    Yoga.nodeStyleSetHeight(root, 320);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetHeightPercent(root_child0, 100);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetHeightPercent(root_child1, 100);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child1_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1_child0, 1);
    Yoga.nodeStyleSetWidthPercent(root_child1_child0, 100);
    Yoga.nodeInsertChild(root_child1, root_child1_child0, 0);

    var root_child1_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1_child1, 1);
    Yoga.nodeStyleSetWidthPercent(root_child1_child1, 100);
    Yoga.nodeInsertChild(root_child1, root_child1_child1, 1);

    var root_child1_child1_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1_child1_child0, 1);
    Yoga.nodeStyleSetWidthPercent(root_child1_child1_child0, 100);
    Yoga.nodeInsertChild(root_child1_child1, root_child1_child1_child0, 0);

    var root_child1_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1_child2, 1);
    Yoga.nodeStyleSetWidthPercent(root_child1_child2, 100);
    Yoga.nodeInsertChild(root_child1, root_child1_child2, 2);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetHeightPercent(root_child2, 100);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(640, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(213, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(213, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child1));
    Assert.floatEquals(107, Yoga.nodeLayoutGetTop(root_child1_child1));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child1));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child1_child0));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child1_child0));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child2));
    Assert.floatEquals(213, Yoga.nodeLayoutGetTop(root_child1_child2));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child2));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child1_child2));

    Assert.floatEquals(427, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(213, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(640, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(427, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(213, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(213, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child1));
    Assert.floatEquals(107, Yoga.nodeLayoutGetTop(root_child1_child1));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child1));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child1_child0));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child1_child0));
    Assert.floatEquals(106, Yoga.nodeLayoutGetHeight(root_child1_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child2));
    Assert.floatEquals(213, Yoga.nodeLayoutGetTop(root_child1_child2));
    Assert.floatEquals(214, Yoga.nodeLayoutGetWidth(root_child1_child2));
    Assert.floatEquals(107, Yoga.nodeLayoutGetHeight(root_child1_child2));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(213, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(320, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeFreeRecursive(root);

    Yoga.configFree(config);
  }

}
