/**
 * Copyright (c) 2014-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @Generated by gentest/gentest.rb from gentest/fixtures/YogaDisplaySpec.html


using facebook.yoga.Enums;

import facebook.Yoga;

import facebook.yoga.*;

import utest.Assert;

class YogaDisplaySpec {

  public function new(){}
  public function test_display_none() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetDisplay(root_child1, Display.None);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_display_none_fixed_size() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetWidth(root_child1, 20);
    Yoga.nodeStyleSetHeight(root_child1, 20);
    Yoga.nodeStyleSetDisplay(root_child1, Display.None);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_display_none_with_margin() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Left, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Top, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Right, 10);
    Yoga.nodeStyleSetMargin(root_child0, Edge.Bottom, 10);
    Yoga.nodeStyleSetWidth(root_child0, 20);
    Yoga.nodeStyleSetHeight(root_child0, 20);
    Yoga.nodeStyleSetDisplay(root_child0, Display.None);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child1));
  }

  public function test_display_none_with_child() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeStyleSetFlexShrink(root_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child0, 0);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetFlexShrink(root_child1, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1, 0);
    Yoga.nodeStyleSetDisplay(root_child1, Display.None);
    Yoga.nodeInsertChild(root, root_child1, 1);

    var root_child1_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1_child0, 1);
    Yoga.nodeStyleSetFlexShrink(root_child1_child0, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child1_child0, 0);
    Yoga.nodeStyleSetWidth(root_child1_child0, 20);
    Yoga.nodeInsertChild(root_child1, root_child1_child0, 0);

    var root_child2 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child2, 1);
    Yoga.nodeStyleSetFlexShrink(root_child2, 1);
    Yoga.nodeStyleSetFlexBasisPercent(root_child2, 0);
    Yoga.nodeInsertChild(root, root_child2, 2);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(50, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child2));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child2));
    Assert.floatEquals(50, Yoga.nodeLayoutGetWidth(root_child2));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child2));
  }

  public function test_display_none_with_position() {
    var config = Config.init();

    var root = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexDirection(root, FlexDirection.Row);
    Yoga.nodeStyleSetWidth(root, 100);
    Yoga.nodeStyleSetHeight(root, 100);

    var root_child0 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child0, 1);
    Yoga.nodeInsertChild(root, root_child0, 0);

    var root_child1 = Yoga.newNodeWithConfig(config);
    Yoga.nodeStyleSetFlexGrow(root_child1, 1);
    Yoga.nodeStyleSetPosition(root_child1, Edge.Top, 10);
    Yoga.nodeStyleSetDisplay(root_child1, Display.None);
    Yoga.nodeInsertChild(root, root_child1, 1);
    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.LTR);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));

    Yoga.nodeCalculateLayout(root, Constants.Undefined, Constants.Undefined, Direction.RTL);

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child0));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetWidth(root_child0));
    Assert.floatEquals(100, Yoga.nodeLayoutGetHeight(root_child0));

    Assert.floatEquals(0, Yoga.nodeLayoutGetLeft(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetTop(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetWidth(root_child1));
    Assert.floatEquals(0, Yoga.nodeLayoutGetHeight(root_child1));
  }

}
